# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for the standalone SHARPpy Reimagined GUI (.exe).

Builds a windowed executable (no console), in the recommended one-folder layout
by default or as an explicitly selected portable one-file bundle, that includes:

* the ``sharpmod`` package (with its TTF fonts + UWyo station catalogue),
* the vendored upstream ``sharppy`` render stack (with its ``databases`` +
  ``datasources`` data files and all decoder submodules),
* the scientific runtime (``metpy``/``pint``/``ecape``/``scipy``) that the
  derived-parameter layer needs at runtime,
* live model/ERA5 retrieval (``herbie``/``cdsapi``/``cfgrib``/``eccodes``)
  and raw WRF NetCDF extraction (``netCDF4``),
  including ecCodes' Windows DLL and Herbie's model templates, plus the
  ``numcodecs``/``pyproj`` runtime used by fast HRRR Zarr point extraction.

Build from the repository root with::

    pyinstaller packaging/sharpmod_gui.spec --noconfirm

The result is ``dist/SHARPpy-Reimagined/SHARPpy-Reimagined.exe`` (one-folder
build -- fast start-up and easiest to debug). Flip ``ONEFILE = True`` below for
a single self-extracting ``dist/SHARPpy-Reimagined.exe`` instead.
"""

import glob
import importlib.machinery
import importlib.util
import os
import runpy

from PyInstaller.utils.hooks import (
    collect_all,
    collect_data_files,
    collect_submodules,
    copy_metadata,
)

# --- one-folder (default) vs one-file toggle --------------------------------
# Overridable from the environment so we can build either layout without editing
# the spec:  set SHARPMOD_ONEFILE=1 for a single self-extracting .exe.
ONEFILE = os.environ.get("SHARPMOD_ONEFILE", "0") == "1"
RELEASE_BUILD = os.environ.get("SHARPMOD_RELEASE_BUILD", "0") == "1"

# Resolve every release field from the checked-out source, then validate the
# installed metadata before PyInstaller can copy it. This fails closed when an
# older editable install or a stale in-tree ``sharpmod.egg-info`` shadows the
# wheel that the official workflow installs.
_REPO = os.path.dirname(SPECPATH)  # SPECPATH is this spec's dir (packaging/)
_CONTRACT = runpy.run_path(os.path.join(SPECPATH, "release_contract.py"))
_SOURCE_VERSION = _CONTRACT["read_source_version"](_REPO)
_METADATA_REPORT = _CONTRACT["validate_installed_sharpmod"](
    _REPO,
    require_dist_info=RELEASE_BUILD,
    require_external_metadata=RELEASE_BUILD,
)
_WINDOWS_VERSION_INFO = _CONTRACT["build_windows_version_info"](_REPO)
_SHARPMOD_METADATA = copy_metadata("sharpmod")
if len(_SHARPMOD_METADATA) != 1:
    raise RuntimeError(
        "expected exactly one installed sharpmod metadata directory, found "
        f"{_SHARPMOD_METADATA!r}"
    )
_metadata_source, _metadata_destination = _SHARPMOD_METADATA[0]
if os.path.normcase(os.path.abspath(_metadata_source)) != os.path.normcase(
    _METADATA_REPORT["metadata_path"]
):
    raise RuntimeError(
        "PyInstaller selected different sharpmod metadata than the validated "
        f"distribution: {_metadata_source!r} != "
        f"{_METADATA_REPORT['metadata_path']!r}"
    )
if RELEASE_BUILD and not _metadata_destination.lower().endswith(".dist-info"):
    raise RuntimeError(
        "official releases must bundle wheel-style sharpmod .dist-info; found "
        f"{_metadata_destination!r}"
    )
print(
    "Validated frozen release metadata: "
    f"version={_SOURCE_VERSION}, path={_metadata_source}"
)

datas = []
binaries = []
hiddenimports = []

# --- sharpmod's own bundled resources ---------------------------------------
# ``sharpmod`` is an editable install, so PyInstaller's ``collect_data_files``
# reports it as "not a package" and skips its data. Add the resources the app
# resolves via importlib.resources (fonts, UWyo catalogue, GUI coastlines, and
# the offline CONUS title-place/county indexes) explicitly, preserving the
# package-relative layout the loaders expect.
_RES = os.path.join(_REPO, "sharpmod", "resources")

# Application icon baked into the .exe (and bundled so the running app can set
# its window icon from the same file). Generated by ``packaging/make_icon.py``.
_ICON = os.path.join(_RES, "icons", "app.ico")
_ICON = _ICON if os.path.exists(_ICON) else None
for _ic in glob.glob(os.path.join(_RES, "icons", "*")):
    datas.append((_ic, "sharpmod/resources/icons"))
for _json in glob.glob(os.path.join(_RES, "*.json")):
    datas.append((_json, "sharpmod/resources"))
for _gazetteer in glob.glob(os.path.join(_RES, "*.tsv.gz")):
    datas.append((_gazetteer, "sharpmod/resources"))
for _archive in glob.glob(os.path.join(_RES, "*.zip")):
    datas.append((_archive, "sharpmod/resources"))
for _ttf in glob.glob(os.path.join(_RES, "fonts", "*.ttf")):
    datas.append((_ttf, "sharpmod/resources/fonts"))

# Collect the fork, the vendored render stack, and the scientific runtime in
# full (data files + submodules + any bundled binaries). ``collect_all`` is the
# robust way to pull package data (fonts, station JSON, sharppy databases,
# metpy/pint unit + static data) that would otherwise be missed by a frozen app.
for pkg in (
    "sharpmod", "sharppy", "sutils", "metpy", "pint", "ecape",
    "cdsapi", "ecmwf", "cfgrib", "eccodes", "numcodecs", "pyproj",
    "netCDF4", "cftime",
):
    try:
        d, b, h = collect_all(pkg)
        if pkg == "sharpmod":
            # ``collect_all`` copies distribution metadata as a side effect.
            # Discard it and add only the exact metadata validated above so an
            # alternate egg-info/dist-info directory cannot enter the bundle.
            d = [
                item for item in d
                if not _CONTRACT["is_sharpmod_metadata_destination"](item[1])
            ]
        datas += d
        binaries += b
        hiddenimports += h
    except Exception:
        # A package that is not installed (e.g. an optional extra) is skipped;
        # the app degrades gracefully at runtime.
        pass

datas += _SHARPMOD_METADATA

# Rust release contract: official binaries set SHARPMOD_REQUIRE_RUST=1 and must
# fail closed if the native extension cannot be collected.  Keeping the flag
# explicit preserves ordinary source and Python-only PyInstaller builds, where
# Rust remains an opportunistic acceleration when it is installed.
_RUST_BACKEND_REQUIRED = (
    os.environ.get("SHARPMOD_REQUIRE_RUST", "0") == "1"
)
try:
    _RUST_BACKEND_SPEC = importlib.util.find_spec("sharpmod_rs")
except (AttributeError, ImportError, ValueError):
    _RUST_BACKEND_SPEC = None

if _RUST_BACKEND_SPEC is not None:
    try:
        d, b, h = collect_all("sharpmod_rs")
        _RUST_NATIVE_SPEC = importlib.util.find_spec("sharpmod_rs.sharpmod_rs")
        _RUST_NATIVE_ORIGIN = (
            None if _RUST_NATIVE_SPEC is None else _RUST_NATIVE_SPEC.origin
        )
        if not _RUST_NATIVE_ORIGIN or not any(
            _RUST_NATIVE_ORIGIN.endswith(suffix)
            for suffix in importlib.machinery.EXTENSION_SUFFIXES
        ):
            raise RuntimeError(
                "release requires the sharpmod_rs native extension"
            )

        datas += d
        binaries += b
        hiddenimports += h
        hiddenimports += ["sharpmod_rs", "sharpmod_rs.sharpmod_rs"]
        # collect_all identifies the extension as a hidden import, but adding
        # its origin explicitly makes the release collection requirement
        # inspectable and independent of PyInstaller hook-discovery changes.
        binaries.append((_RUST_NATIVE_ORIGIN, "sharpmod_rs"))
    except Exception as exc:
        if _RUST_BACKEND_REQUIRED:
            raise RuntimeError(
                "release requires collecting sharpmod_rs"
            ) from exc
        # A broken extension must not prevent an explicitly Python-only bundle,
        # but make the downgrade visible in the PyInstaller build log.
        print(
            "WARNING: could not collect sharpmod_rs; building a Python-only "
            f"bundle ({type(exc).__name__}: {exc})"
        )
elif _RUST_BACKEND_REQUIRED:
    raise RuntimeError(
        "release requires the sharpmod_rs native extension"
    )

# Herbie's model definitions are runtime modules, but its optional plotting
# toolbox imports cartopy. Collect the operational package while omitting that
# unused optional branch. PyInstaller's maintained xarray hook handles xarray
# itself and avoids dragging its test suite into the frozen application.
datas += collect_data_files("herbie")
hiddenimports += collect_submodules(
    "herbie",
    filter=lambda name: not name.startswith("herbie.toolbox"),
    on_error="ignore",
)
hiddenimports += ["xarray", "cfgrib.xarray_plugin", "netCDF4", "cftime"]

# The decoder registry imports these vendored decoders dynamically
# (sharpmod.io.decoder.findDecoders); name them so the freezer keeps them.
hiddenimports += [
    "sharppy.io.buf_decoder",
    "sharppy.io.spc_decoder",
    "sharppy.io.pecan_decoder",
    "sharppy.io.arw_decoder",
    "sharppy.io.uwyo_decoder",
]

# scipy/pandas/numpy are pulled in transitively by metpy and handled well by
# PyInstaller's own hooks + dependency graph, so we do NOT ``collect_submodules``
# them (that would drag in their massive ``.tests`` trees and bloat the bundle).
# Only name the small pure-python helpers the freezer can miss.
hiddenimports += ["dateutil", "certifi", "requests"]

block_cipher = None

a = Analysis(
    ["sharpmod_gui_launcher.py"],
    pathex=[_REPO],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    # Trim heavyweight, GUI-irrelevant optional deps to keep the bundle smaller.
    excludes=["tkinter", "PyQt5", "PyQt6", "PySide2", "IPython", "notebook",
              "pytest", "hypothesis",
              # Test trees dragged in by scientific deps -- never needed at run.
              "pandas.tests", "scipy.tests", "numpy.tests", "matplotlib.tests",
              "xarray.tests", "sharpmod.tests",
              # Optional Herbie plotting helpers require cartopy; forecast
              # inventory/download/xarray support does not use this toolbox.
              "herbie.toolbox",
              # pyarrow (~47 MB of arrow*.dll) is only used by pandas for
              # parquet/arrow-backed frames, which this app never touches.
              "pyarrow",
              # Unused PySide6 modules. The app is pure QtWidgets + QPainter
              # (via qtpy), so drop the large optional Qt feature libraries.
              "PySide6.QtDataVisualization", "PySide6.QtCharts",
              "PySide6.QtQuick", "PySide6.QtQuick3D", "PySide6.QtQml",
              "PySide6.QtQuickWidgets", "PySide6.QtQuickControls2",
              "PySide6.Qt3DCore", "PySide6.Qt3DRender", "PySide6.Qt3DInput",
              "PySide6.Qt3DAnimation", "PySide6.Qt3DExtras",
              "PySide6.QtWebEngineCore", "PySide6.QtWebEngineWidgets",
              "PySide6.QtWebEngineQuick", "PySide6.QtWebChannel",
              "PySide6.QtWebSockets", "PySide6.QtMultimedia",
              "PySide6.QtMultimediaWidgets", "PySide6.QtPdf",
              "PySide6.QtPdfWidgets", "PySide6.QtDesigner",
              "PySide6.QtBluetooth", "PySide6.QtNfc", "PySide6.QtPositioning",
              "PySide6.QtSensors", "PySide6.QtSerialPort",
              "PySide6.QtSql", "PySide6.QtTest", "PySide6.QtHelp",
              "PySide6.QtScxml", "PySide6.QtCharts"],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    # Keep Python bytecode in the fast PYZ archive. The recommended one-folder
    # build sideloads its PKG beside the launcher below, so the PE itself does
    # not need a large opaque archive appended to it.
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

if ONEFILE:
    exe = EXE(
        pyz,
        a.scripts,
        a.binaries,
        a.zipfiles,
        a.datas,
        [],
        name="SHARPpy-Reimagined",
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=False,
        upx_exclude=[],
        runtime_tmpdir=None,
        console=False,  # windowed GUI app -- no console window
        disable_windowed_traceback=False,
        argv_emulation=False,
        target_arch=None,
        codesign_identity=None,
        entitlements_file=None,
        icon=_ICON,
        version=_WINDOWS_VERSION_INFO,
    )
else:
    exe = EXE(
        pyz,
        a.scripts,
        [],
        exclude_binaries=True,
        name="SHARPpy-Reimagined",
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=False,
        console=False,  # windowed GUI app -- no console window
        disable_windowed_traceback=False,
        argv_emulation=False,
        target_arch=None,
        codesign_identity=None,
        entitlements_file=None,
        icon=_ICON,
        version=_WINDOWS_VERSION_INFO,
        append_pkg=False,
    )
    coll = COLLECT(
        exe,
        a.binaries,
        a.zipfiles,
        a.datas,
        strip=False,
        upx=False,
        upx_exclude=[],
        name="SHARPpy-Reimagined",
    )
