# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for the standalone SHARPpy Reimagined GUI (.exe).

Builds a single windowed executable (no console) that bundles:

* the ``sharpmod`` package (with its TTF fonts + UWyo station catalogue),
* the vendored upstream ``sharppy`` render stack (with its ``databases`` +
  ``datasources`` data files and all decoder submodules),
* the scientific runtime (``metpy``/``pint``/``ecape``/``scipy``) that the
  derived-parameter layer needs at runtime,
* live model/ERA5 retrieval (``herbie``/``cdsapi``/``cfgrib``/``eccodes``),
  including ecCodes' Windows DLL and Herbie's model templates, plus the
  ``numcodecs``/``pyproj`` runtime used by fast HRRR Zarr point extraction.

Build from the repository root with::

    pyinstaller packaging/sharpmod_gui.spec --noconfirm

The result is ``dist/SHARPpy-Reimagined/SHARPpy-Reimagined.exe`` (one-folder
build -- fast start-up and easiest to debug). Flip ``ONEFILE = True`` below for
a single self-extracting ``dist/SHARPpy-Reimagined.exe`` instead.
"""

import glob
import os

from PyInstaller.utils.hooks import (
    collect_all,
    collect_data_files,
    collect_submodules,
)

# --- one-folder (default) vs one-file toggle --------------------------------
# Overridable from the environment so we can build either layout without editing
# the spec:  set SHARPMOD_ONEFILE=1 for a single self-extracting .exe.
ONEFILE = os.environ.get("SHARPMOD_ONEFILE", "0") == "1"

datas = []
binaries = []
hiddenimports = []

# --- sharpmod's own bundled resources ---------------------------------------
# ``sharpmod`` is an editable install, so PyInstaller's ``collect_data_files``
# reports it as "not a package" and skips its data. Add the resources the app
# resolves via importlib.resources (fonts, UWyo catalogue, GUI coastlines)
# explicitly, preserving the package-relative layout the loaders expect.
_REPO = os.path.dirname(SPECPATH)  # SPECPATH is this spec's dir (packaging/)
_RES = os.path.join(_REPO, "sharpmod", "resources")

# Application icon baked into the .exe (and bundled so the running app can set
# its window icon from the same file). Generated by ``packaging/make_icon.py``.
_ICON = os.path.join(_RES, "icons", "app.ico")
_ICON = _ICON if os.path.exists(_ICON) else None
for _ic in glob.glob(os.path.join(_RES, "icons", "*")):
    datas.append((_ic, "sharpmod/resources/icons"))
for _json in glob.glob(os.path.join(_RES, "*.json")):
    datas.append((_json, "sharpmod/resources"))
for _ttf in glob.glob(os.path.join(_RES, "fonts", "*.ttf")):
    datas.append((_ttf, "sharpmod/resources/fonts"))

# Collect the fork, the vendored render stack, and the scientific runtime in
# full (data files + submodules + any bundled binaries). ``collect_all`` is the
# robust way to pull package data (fonts, station JSON, sharppy databases,
# metpy/pint unit + static data) that would otherwise be missed by a frozen app.
for pkg in (
    "sharpmod", "sharppy", "sutils", "metpy", "pint", "ecape",
    "cdsapi", "ecmwf", "cfgrib", "eccodes", "numcodecs", "pyproj",
):
    try:
        d, b, h = collect_all(pkg)
        datas += d
        binaries += b
        hiddenimports += h
    except Exception:
        # A package that is not installed (e.g. an optional extra) is skipped;
        # the app degrades gracefully at runtime.
        pass

# Herbie's model definitions are runtime modules, but its optional plotting
# toolbox imports cartopy. Collect the operational package while omitting that
# unused optional branch. PyInstaller's maintained xarray hook handles xarray
# itself and avoids dragging its test suite into the frozen application.
datas += collect_data_files("herbie")
hiddenimports += collect_submodules(
    "herbie",
    filter=lambda name: not name.startswith("herbie.toolbox"),
    on_error="ignore",
)
hiddenimports += ["xarray", "cfgrib.xarray_plugin"]

# The decoder registry imports these vendored decoders dynamically
# (sharpmod.io.decoder.findDecoders); name them so the freezer keeps them.
hiddenimports += [
    "sharppy.io.buf_decoder",
    "sharppy.io.spc_decoder",
    "sharppy.io.pecan_decoder",
    "sharppy.io.arw_decoder",
    "sharppy.io.uwyo_decoder",
]

# scipy/pandas/numpy are pulled in transitively by metpy and handled well by
# PyInstaller's own hooks + dependency graph, so we do NOT ``collect_submodules``
# them (that would drag in their massive ``.tests`` trees and bloat the bundle).
# Only name the small pure-python helpers the freezer can miss.
hiddenimports += ["dateutil", "certifi", "requests"]

block_cipher = None

a = Analysis(
    ["sharpmod_gui_launcher.py"],
    pathex=[_REPO],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    # Trim heavyweight, GUI-irrelevant optional deps to keep the bundle smaller.
    excludes=["tkinter", "PyQt5", "PyQt6", "PySide2", "IPython", "notebook",
              "pytest", "hypothesis", "netCDF4",
              # Test trees dragged in by scientific deps -- never needed at run.
              "pandas.tests", "scipy.tests", "numpy.tests", "matplotlib.tests",
              "xarray.tests", "sharpmod.tests",
              # Optional Herbie plotting helpers require cartopy; forecast
              # inventory/download/xarray support does not use this toolbox.
              "herbie.toolbox",
              # pyarrow (~47 MB of arrow*.dll) is only used by pandas for
              # parquet/arrow-backed frames, which this app never touches.
              "pyarrow",
              # Unused PySide6 modules. The app is pure QtWidgets + QPainter
              # (via qtpy), so drop the large optional Qt feature libraries.
              "PySide6.QtDataVisualization", "PySide6.QtCharts",
              "PySide6.QtQuick", "PySide6.QtQuick3D", "PySide6.QtQml",
              "PySide6.QtQuickWidgets", "PySide6.QtQuickControls2",
              "PySide6.Qt3DCore", "PySide6.Qt3DRender", "PySide6.Qt3DInput",
              "PySide6.Qt3DAnimation", "PySide6.Qt3DExtras",
              "PySide6.QtWebEngineCore", "PySide6.QtWebEngineWidgets",
              "PySide6.QtWebEngineQuick", "PySide6.QtWebChannel",
              "PySide6.QtWebSockets", "PySide6.QtMultimedia",
              "PySide6.QtMultimediaWidgets", "PySide6.QtPdf",
              "PySide6.QtPdfWidgets", "PySide6.QtDesigner",
              "PySide6.QtBluetooth", "PySide6.QtNfc", "PySide6.QtPositioning",
              "PySide6.QtSensors", "PySide6.QtSerialPort",
              "PySide6.QtSql", "PySide6.QtTest", "PySide6.QtHelp",
              "PySide6.QtScxml", "PySide6.QtCharts"],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

if ONEFILE:
    exe = EXE(
        pyz,
        a.scripts,
        a.binaries,
        a.zipfiles,
        a.datas,
        [],
        name="SHARPpy-Reimagined",
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=True,
        upx_exclude=[],
        runtime_tmpdir=None,
        console=False,  # windowed GUI app -- no console window
        disable_windowed_traceback=False,
        argv_emulation=False,
        target_arch=None,
        codesign_identity=None,
        entitlements_file=None,
        icon=_ICON,
    )
else:
    exe = EXE(
        pyz,
        a.scripts,
        [],
        exclude_binaries=True,
        name="SHARPpy-Reimagined",
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=True,
        console=False,  # windowed GUI app -- no console window
        disable_windowed_traceback=False,
        argv_emulation=False,
        target_arch=None,
        codesign_identity=None,
        entitlements_file=None,
        icon=_ICON,
    )
    coll = COLLECT(
        exe,
        a.binaries,
        a.zipfiles,
        a.datas,
        strip=False,
        upx=True,
        upx_exclude=[],
        name="SHARPpy-Reimagined",
    )
